#!/usr/bin/env/python3
# -*- coding:utf-8 -*-

from functools import reduce

def fn(x,y):
    return x + y

if __name__ == '__main__':
    in_put = input('enter something: ')
    reverse_list = list(in_put)[::-1]  #将输入转换为列表之后倒置
    out_put = reduce(fn, reverse_list) #将列表重新组合成字符串
    print(out_put)
