#!usr/bin/env/python3
# -*- coding:utf-8 -*-

########################################
#   新建一个空字符串C
#       取出B中的第一个数，并删除这个数
#       将A中对应索引位置的字符取出，放在C的表尾
#       循环此操作直到B成为空数组
#       得C
#       若设定的循环为N，则循环N次
########################################
import pdb

def decode_a(a, b, n):
    c = ''
    for i in range(n):
        if len(c) != 0:
            a = c
            c = ''
        for i in range(len(a)):
#            pdb.set_trace()
            temp2 = a[b[i]]
            c = c + temp2
    return c

if __name__ == "__main__":
    a = input("输入源码")
    b = eval(input("输入密码表"))
    n = int(input("输入解码次数"))
    print(decode_a(a,b,n))

#输入："ABC" [2,0,1] 2            输出："BCA"
#输入："ABCD" [3,2,1,0] 1         输出："DCBA"
#输入："12345" [3,1,2,4,0] 1      输出："42351"    
